# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eps <- function(a) {
    .Call(`_scCNMF_eps`, a)
}

CppoperationMA_demo <- function(M, A, type) {
    .Call(`_scCNMF_CppoperationMA_demo`, M, A, type)
}

ifzeroMCPP <- function(M) {
    .Call(`_scCNMF_ifzeroMCPP`, M)
}

chooesVinMCPP <- function(M, A, type) {
    .Call(`_scCNMF_chooesVinMCPP`, M, A, type)
}

epsMCpp <- function(M) {
    .Call(`_scCNMF_epsMCpp`, M)
}

Cvar <- function(AA, Mean, length) {
    .Call(`_scCNMF_Cvar`, AA, Mean, length)
}

Cttest <- function(A, B, AA, BB, lengthA, lengthB) {
    .Call(`_scCNMF_Cttest`, A, B, AA, BB, lengthA, lengthB)
}

scCNMF_cpp_function <- function(X1, X2, Reg, K, maxIter, stop_rule, alpha, beta, gamma, W10, W20, W30, H0, θ0, O0, c1, c2, Reg_w, core) {
    .Call(`_scCNMF_scCNMF_cpp_function`, X1, X2, Reg, K, maxIter, stop_rule, alpha, beta, gamma, W10, W20, W30, H0, θ0, O0, c1, c2, Reg_w, core)
}

Fold_RE_TG_MultiAdjustCore <- function(X1, X2, GeneLoc, PeakLoc) {
    .Call(`_scCNMF_Fold_RE_TG_MultiAdjustCore`, X1, X2, GeneLoc, PeakLoc)
}

